// generated by brock sync, do not edit
import type { RendererBootTask } from '@drizztdourden08/brock-react';
import runsTask from '../src/boot/runs.task';
import searchActionsTask from '../src/boot/search-actions.task';
import sessionEventsTask from '../src/boot/session-events.task';
import sessionViewRelayTask from '../src/boot/session-view-relay.task';

const rendererBootTasks: RendererBootTask[] = [
  { ...runsTask, id: 'runs' },
  { ...searchActionsTask, id: 'search-actions' },
  { ...sessionEventsTask, id: 'session-events' },
  { ...sessionViewRelayTask, id: 'session-view-relay' },
];

export { rendererBootTasks };
