// generated by brock sync, do not edit
import type { HandlerGroup } from '@drizztdourden08/brock-electron/main';
import { engineHandlers } from '../electron/handlers/engine-handlers';
import { gamesHandlers } from '../electron/handlers/games-handlers';
import { ggHandlers } from '../electron/handlers/gg-handlers';
import { libraryHandlers } from '../electron/handlers/library-handlers';
import { serverHandlers } from '../electron/handlers/server-handlers';
import { sessionHandlers } from '../electron/handlers/session-handlers';

const mainHandlers: HandlerGroup[] = [engineHandlers, gamesHandlers, ggHandlers, libraryHandlers, serverHandlers, sessionHandlers];

export { mainHandlers };
