// generated by brock sync, do not edit
import type { RendererModule } from '@drizztdourden08/brock-react';
import secretsRenderer from '@drizztdourden08/brock-secrets/renderer';
import updaterRenderer from '@drizztdourden08/brock-updater/renderer';

const rendererModules: RendererModule[] = [
  secretsRenderer,
  updaterRenderer,
];

export { rendererModules };
