// generated by brock sync, do not edit
import type { RendererModule } from '@drizztdourden08/brock-react';
import secretsRenderer from '@drizztdourden08/brock-secrets/renderer';

const rendererModules: RendererModule[] = [
  secretsRenderer,
];

export { rendererModules };
