// generated by brock sync, do not edit
import type { PreloadNamespace } from '@drizztdourden08/brock-electron/preload';
import secretsPreload from '@drizztdourden08/brock-secrets/preload';
import updaterPreload from '@drizztdourden08/brock-updater/preload';

const preloadNamespaces: PreloadNamespace[] = [
  secretsPreload,
  updaterPreload,
];

export { preloadNamespaces };
