// generated by brock sync, do not edit
import type { MainModule } from '@drizztdourden08/brock-electron/main';
import secretsMain from '@drizztdourden08/brock-secrets/main';

const mainModules: MainModule[] = [
  secretsMain,
];

export { mainModules };
