// generated by brock sync, do not edit
import { buildScreenTree } from '@drizztdourden08/brock-react';
import config from '../src/screens/screens.config';
import { searchIndex } from './search';
import DataOldRunsPage, { meta as dataOldRunsPageMeta } from '../src/screens/data/old-runs.page';
import DataStoragePage, { meta as dataStoragePageMeta } from '../src/screens/data/storage.page';
import MultiworldAppEnginePage, { meta as multiworldAppEnginePageMeta } from '../src/screens/multiworld/app/engine.page';
import MultiworldAppGeneralSettings, { meta as multiworldAppGeneralSettingsMeta } from '../src/screens/multiworld/app/general.settings';
import MultiworldHomeHero, { meta as multiworldHomeHeroMeta } from '../src/screens/multiworld/home.hero';
import MultiworldHostingArchipelagoGgSettings, { meta as multiworldHostingArchipelagoGgSettingsMeta } from '../src/screens/multiworld/hosting/archipelago-gg.settings';
import MultiworldHostingHostingSettings, { meta as multiworldHostingHostingSettingsMeta } from '../src/screens/multiworld/hosting/hosting.settings';
import MultiworldHostingServersPage, { meta as multiworldHostingServersPageMeta } from '../src/screens/multiworld/hosting/servers.page';
import MultiworldLibraryGamesCommunityTab, { meta as multiworldLibraryGamesCommunityTabMeta } from '../src/screens/multiworld/library/games/community.tab';
import MultiworldLibraryGamesInstalledTab, { meta as multiworldLibraryGamesInstalledTabMeta } from '../src/screens/multiworld/library/games/installed.tab';
import MultiworldLibraryGamesOfficialTab, { meta as multiworldLibraryGamesOfficialTabMeta } from '../src/screens/multiworld/library/games/official.tab';
import MultiworldLibraryGamesUpdatesTab, { meta as multiworldLibraryGamesUpdatesTabMeta } from '../src/screens/multiworld/library/games/updates.tab';
import { meta as multiworldLibraryGamesPageMetaMeta } from '../src/screens/multiworld/library/games.page';
import MultiworldLibraryPresetsPage, { meta as multiworldLibraryPresetsPageMeta } from '../src/screens/multiworld/library/presets.page';
import MultiworldLibrarySessionsEditSub, { meta as multiworldLibrarySessionsEditSubMeta } from '../src/screens/multiworld/library/sessions/edit.sub';
import MultiworldLibrarySessionsNewSub, { meta as multiworldLibrarySessionsNewSubMeta } from '../src/screens/multiworld/library/sessions/new.sub';
import MultiworldLibrarySessionsPage, { meta as multiworldLibrarySessionsPageMeta } from '../src/screens/multiworld/library/sessions.page';
import SessionBase, { meta as sessionBaseMeta } from '../src/screens/session.base';

const screenTree = buildScreenTree(config, [
  { kind: 'page', bucket: 'data', id: 'old-runs', component: DataOldRunsPage, meta: dataOldRunsPageMeta },
  { kind: 'page', bucket: 'data', id: 'storage', component: DataStoragePage, meta: dataStoragePageMeta },
  { kind: 'page', bucket: 'multiworld', group: 'app', id: 'engine', component: MultiworldAppEnginePage, meta: multiworldAppEnginePageMeta },
  { kind: 'settings', bucket: 'multiworld', group: 'app', id: 'general', sections: MultiworldAppGeneralSettings, meta: multiworldAppGeneralSettingsMeta },
  { kind: 'hero', bucket: 'multiworld', id: 'home', component: MultiworldHomeHero, meta: multiworldHomeHeroMeta },
  { kind: 'settings', bucket: 'multiworld', group: 'hosting', id: 'archipelago-gg', sections: MultiworldHostingArchipelagoGgSettings, meta: multiworldHostingArchipelagoGgSettingsMeta },
  { kind: 'settings', bucket: 'multiworld', group: 'hosting', id: 'hosting', sections: MultiworldHostingHostingSettings, meta: multiworldHostingHostingSettingsMeta },
  { kind: 'page', bucket: 'multiworld', group: 'hosting', id: 'servers', component: MultiworldHostingServersPage, meta: multiworldHostingServersPageMeta },
  { kind: 'tab', bucket: 'multiworld', group: 'library', page: 'games', id: 'community', component: MultiworldLibraryGamesCommunityTab, meta: multiworldLibraryGamesCommunityTabMeta },
  { kind: 'tab', bucket: 'multiworld', group: 'library', page: 'games', id: 'installed', component: MultiworldLibraryGamesInstalledTab, meta: multiworldLibraryGamesInstalledTabMeta },
  { kind: 'tab', bucket: 'multiworld', group: 'library', page: 'games', id: 'official', component: MultiworldLibraryGamesOfficialTab, meta: multiworldLibraryGamesOfficialTabMeta },
  { kind: 'tab', bucket: 'multiworld', group: 'library', page: 'games', id: 'updates', component: MultiworldLibraryGamesUpdatesTab, meta: multiworldLibraryGamesUpdatesTabMeta },
  { kind: 'page-meta', bucket: 'multiworld', group: 'library', id: 'games', meta: multiworldLibraryGamesPageMetaMeta },
  { kind: 'page', bucket: 'multiworld', group: 'library', id: 'presets', component: MultiworldLibraryPresetsPage, meta: multiworldLibraryPresetsPageMeta },
  { kind: 'sub', bucket: 'multiworld', group: 'library', page: 'sessions', id: 'edit', component: MultiworldLibrarySessionsEditSub, meta: multiworldLibrarySessionsEditSubMeta },
  { kind: 'sub', bucket: 'multiworld', group: 'library', page: 'sessions', id: 'new', component: MultiworldLibrarySessionsNewSub, meta: multiworldLibrarySessionsNewSubMeta },
  { kind: 'page', bucket: 'multiworld', group: 'library', id: 'sessions', component: MultiworldLibrarySessionsPage, meta: multiworldLibrarySessionsPageMeta },
  { kind: 'base', id: 'session', component: SessionBase, meta: sessionBaseMeta },
], searchIndex);

export { screenTree };
