// generated by brock sync, do not edit
import { buildSearchIndex } from '@drizztdourden08/brock-react';
import config from '../src/screens/screens.config';

const searchIndex = buildSearchIndex(config, [
  {"kind":"page","id":"old-runs","bucket":"data","title":"Old runs","icon":"history","keywords":["session","runs","clean","old"]},
  {"kind":"page","id":"storage","bucket":"data","title":"Storage","icon":"hard-drive","keywords":["sizes","folder","disk","export","import","backup","zip"]},
  {"kind":"page","id":"engine","bucket":"multiworld","group":"app","title":"Engine","icon":"cpu","keywords":["archipelago","python","generator","setup","rebuild"]},
  {"kind":"settings","id":"general","bucket":"multiworld","group":"app","title":"General","icon":"settings","keywords":["window","fullscreen","developer","logging"],"sections":[{"id":"window","title":"Window","rows":[{"key":"windowMode","label":"Window mode","description":"Windowed, borderless or fullscreen.","hint":"Borderless and fullscreen hide the title bar.","keywords":[]},{"key":"startFullscreen","label":"Start fullscreen","description":"Open in fullscreen on launch.","hint":"Applies the next time Archipelia starts.","keywords":[]}]},{"id":"developer","title":"Developer","rows":[{"key":"developerToolsEnabled","label":"Developer tools","description":"Allow opening the developer tools.","hint":"Adds the developer console to the menu.","keywords":[]},{"key":"allowDebugLogging","label":"Debug logging","description":"Write debug lines to the session log.","hint":"Makes the log larger; turn it on to report a problem.","keywords":[]}]}]},
  {"kind":"hero","id":"home","bucket":"multiworld","title":"Home","icon":"house","keywords":["overview","engine","recent","runs","run","again"]},
  {"kind":"settings","id":"archipelago-gg","bucket":"multiworld","group":"hosting","title":"archipelago.gg","icon":"globe","keywords":["website","rooms","owner","online","host"],"sections":[{"id":"website","title":"Website","rows":[{"key":"ggBaseUrl","label":"Site","description":"The Archipelago website that hosts the rooms of sessions run there.","hint":"Change only for a self-hosted copy of the Archipelago website.","keywords":["url","self-hosted","website","address"]}]},{"id":"owner","title":"Owner id","rows":[{"key":"ggOwner","label":"Owner id","description":"The site has no accounts: rooms belong to a private owner id that Archipelia keeps in the vault, so only this app can command them or read their logs.","hint":"Forgetting the owner id loses control of its rooms. One is made the first time a session runs there.","keywords":["rooms","browser","open","forget","reset","vault"]}]}]},
  {"kind":"settings","id":"hosting","bucket":"multiworld","group":"hosting","title":"Hosting","icon":"radio","keywords":["defaults","port","server","release","collect","hints"],"sections":[{"id":"new-sessions","title":"New sessions","rows":[{"key":"hostingDefaultHost","label":"Default host","description":"Where a new session runs its server.","hint":"Each session keeps its own copy, so changing this never rewrites one.","keywords":["local","archipelago.gg"]}]},{"id":"server-rules","title":"Server rules","rows":[]}]},
  {"kind":"page","id":"servers","bucket":"multiworld","group":"hosting","title":"Servers","icon":"server","keywords":["ssh","remote","host","machine"]},
  {"kind":"tab","id":"community","bucket":"multiworld","group":"library","page":"games","title":"Community","icon":"gamepad-2","keywords":["games","apworld","catalog"]},
  {"kind":"tab","id":"installed","bucket":"multiworld","group":"library","page":"games","title":"Installed","icon":"gamepad-2","keywords":["games","apworld","installed","worlds"]},
  {"kind":"tab","id":"official","bucket":"multiworld","group":"library","page":"games","title":"Official","icon":"gamepad-2","keywords":["games","apworld","catalog"]},
  {"kind":"tab","id":"updates","bucket":"multiworld","group":"library","page":"games","title":"Updates","icon":"gamepad-2","keywords":["games","apworld","new","versions"]},
  {"kind":"page-meta","id":"games","bucket":"multiworld","group":"library","title":"Games","icon":"gamepad-2","keywords":["apworld","install","catalog","worlds"]},
  {"kind":"page","id":"presets","bucket":"multiworld","group":"library","title":"Presets","icon":"sliders-horizontal","keywords":["options","yaml","player","settings"]},
  {"kind":"sub","id":"edit","bucket":"multiworld","group":"library","page":"sessions","title":"Edit session","icon":"pencil","path":":id/edit"},
  {"kind":"sub","id":"new","bucket":"multiworld","group":"library","page":"sessions","title":"New session","icon":"plus","path":"new","keywords":["builder","players","create","session"]},
  {"kind":"page","id":"sessions","bucket":"multiworld","group":"library","title":"Sessions","icon":"layers","keywords":["saved","sessions","runs","new","session","builder"]},
  {"kind":"base","id":"session","title":"Session","icon":"radio"},
]);

export { searchIndex };
