// generated by brock sync, do not edit
import { titleBarFromFiles } from '@drizztdourden08/brock-react';
import hostingItem from '../src/title-bar/hosting.action';

const appTitleBar = titleBarFromFiles([
  { id: 'hosting', source: hostingItem },
]);

export { appTitleBar };
