// generated by brock sync, do not edit
import { widgetsFromFiles } from '@drizztdourden08/brock-react';
import ConsoleWidget, { meta as consoleWidgetMeta } from '../src/widgets/console.widget';
import HintsWidget, { meta as hintsWidgetMeta } from '../src/widgets/hints.widget';
import LogWidget, { meta as logWidgetMeta } from '../src/widgets/log.widget';
import PlayersWidget, { meta as playersWidgetMeta } from '../src/widgets/players.widget';
import RoomWidget, { meta as roomWidgetMeta } from '../src/widgets/room.widget';
import SpoilerWidget, { meta as spoilerWidgetMeta } from '../src/widgets/spoiler.widget';

const appWidgets = widgetsFromFiles([
  { id: 'console', component: ConsoleWidget, meta: consoleWidgetMeta },
  { id: 'hints', component: HintsWidget, meta: hintsWidgetMeta },
  { id: 'log', component: LogWidget, meta: logWidgetMeta },
  { id: 'players', component: PlayersWidget, meta: playersWidgetMeta },
  { id: 'room', component: RoomWidget, meta: roomWidgetMeta },
  { id: 'spoiler', component: SpoilerWidget, meta: spoilerWidgetMeta },
]);
const appWidgetLayout = undefined;

export { appWidgetLayout, appWidgets };
